application:
  version: 1.0
spring:
  batch:
    initialize-schema: always
  datasource:
    url: jdbc:postgresql://188.227.18.141:5432/lib_spring_mvc
    username: temp_user
    password: temp_pas
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  data:
    mongodb:
      authentication-database: admin
      host: 188.227.18.141
      port: 27017
      database: lib_batch
      username: userbatch
      password: batchbatch
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none